#  website setting
title: '胖酒小栈'
# 衡量代码质量的唯一有效标准: WTF/min
# It is better to be clear than to be clever.
# 做的清晰比做的聪明更好
motto: 'It is better to be clear than to be clever'
description: 'stay hungry, stay foolish'
keywords: '胖酒, 胖酒小栈, just, dot, justdot, justdotx, full stack'
timezone: Asia/Shanghai
encoding: "utf-8"
url: 'http://justdot.me'

# mime
author: justdot
belief: '机智的胖酒，全栈开发者 简单快乐的小码农 do._.ob'

# website license
build_date: 2017

# the subpath of your site, e.g. /blog
baseurl: ''
permalink: /:year/:month/:day/:title.html

# github repo setting
# https://help.github.com/articles/repository-metadata-on-github-pages/
repository: sTdobTs/dot-jekyll-theme

# conversion & build setting
markdown: kramdown
highlighter: rouge
kramdown:
    input: GFM

exclude:
  - docs
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CHANGELOG.md
  - .gitignore
  - build.sh
  - startup.sh

# # paginate setting(paginate)
# paginate: 1
# paginate_path: "page:num"

# pagination setting(paginate-v2)
pagination:
  enabled: true

  limit: 0
  per_page: 5

  permalink: '/page/:num/'

  sort_field: 'date'
  sort_reverse: true

  trail: 
    before: 2
    after: 2

# plugins
plugins:
  # - jekyll-paginate
  - jekyll-paginate-v2
  - jekyll-github-metadata
